### ISSUE TITLE
Outbox API not working

### ISSUE THREAD

**Issue by edsilvaseekout** [nylas-samples/node-email-send#1]
Very simple Outbox call using the Nylas Node JS SDK

```
Nylas.config({
    clientId: NYLAS_CLIENT_ID,
    clientSecret: NYLAS_SECRET
});
const nylasConn = Nylas.with(authToken);

const today = new Date();
const soon = new Date(today.setMinutes(today.getMinutes() + 1));

const message = new OutboxMessage(nylasConn, {
    to: [new EmailParticipant({ email: to, name: to })],
    subject: "test subject",
    body: "test body",
    sendAt: soon ,
});

const messageResponse = await message.send();
```

It throws an exception with this error:

```
name:'Bad Request'
statusCode:400
type:'invalid_request_error'
__proto__:Object
message:'No recipients specified'
stack:'Bad Request: No recipients specified\n    at new NylasApiError
```

Error message is not very clear in what I am doing wrong.
Any help?

Thanks.

**Comment by ashryanbeats** [comment]
Thanks for reaching out!

It looks like you're aiming to use the Outbox API, while the original sample here uses our Send API.

For the Outbox API, you'd need to use `nylas.outbox.send()`. This may not solve 100% of your issue but it will be a good place to start.

(Also, I'm assuming you've omitted your declaration of `to` in the `new EmailParticipant` instantiation in order to hide it. Just mentioning it in case: you'll need to define `to`.)

Beyond that, it's worth having a look here, which offers some code examples for the Outbox API, and may have exactly what you're looking for:
https://github.com/nylas/nylas-nodejs/pull/327

I'll work on pushing a dedicated Outbox API send repo, similar to this one, as well.

**Comment by edsilvaseekout** [comment]
It worked for me. Thanks!
